//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfouLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisactivatedAccounts
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public string Reason { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid DisactivatedBy { get; set; }
        public System.DateTime DisactivatedTime { get; set; }
        public int DisactivatedType { get; set; }
    
        public virtual DisactivatedTypes DisactivatedTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
