//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfouLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.BuyerToTicket = new HashSet<BuyerToTicket>();
            this.SellerToTicket = new HashSet<SellerToTicket>();
        }
    
        public System.Guid TicketId { get; set; }
        public System.Guid EventId { get; set; }
        public int Seat { get; set; }
        public System.Guid TicketCode { get; set; }
        public System.DateTime SoldDate { get; set; }
        public System.Guid SoldBy { get; set; }
        public System.Guid BillingId { get; set; }
        public TicketStatus TicketStatus { get; set; }
        public Nullable<int> Placement { get; set; }
    
        public virtual BillingInformation BillingInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerToTicket> BuyerToTicket { get; set; }
        public virtual Events Events { get; set; }
        public virtual Seller Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerToTicket> SellerToTicket { get; set; }
        public virtual TicketPlacementType TicketPlacementType { get; set; }
        public virtual TicketStatuses TicketStatuses { get; set; }
    }
}
