//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfouLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketType()
        {
            this.TicketPool = new HashSet<TicketPool>();
        }
    
        public int TicketTypeId { get; set; }
        public string TicketName { get; set; }
        public decimal TicketPrice { get; set; }
        public int TicketAmount { get; set; }
        public int TicketTypeStatus { get; set; }
        public bool TicketVisibility { get; set; }
        public System.Guid Author { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketPool> TicketPool { get; set; }
        public virtual TicketTypeStatuses TicketTypeStatuses { get; set; }
    }
}
