//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfouLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketPool
    {
        public System.Guid EventId { get; set; }
        public int TicketTypeId { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
