//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confou.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logging
    {
        public int LogId { get; set; }
        public string Action { get; set; }
        public string TargetTable { get; set; }
        public int TargetId { get; set; }
        public int Author { get; set; }
        public string AuthorIP { get; set; }
        public System.DateTime ActionDate { get; set; }
    }
}
